PeerOrgs:

  - Name: Org1
    Domain: org1.trade.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.trade.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 2

  - Name: Org3
    Domain: org3.trade.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 2

OrdererOrgs:
  - Name: Orderer
    Domain: trade.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
