volumes:
  orderer0.trade.com:
  orderer1.trade.com:
  orderer2.trade.com:
  peer0.org1.trade.com:
  peer1.org1.trade.com:
  peer2.org1.trade.com:
  peer0.org2.trade.com:
  peer1.org2.trade.com:
  peer2.org2.trade.com:
  peer0.org3.trade.com:
  peer1.org3.trade.com:
  peer2.org3.trade.com:

networks:
  trade:
    name: trade

x-common: &common
  networks: [ trade ]

x-orderer-common: &orderer-common
  <<: *common
  image: hyperledger/fabric-orderer:2.5
  command: orderer
  working_dir: /root
  env_file:
    - ./environment/orderer.env

x-peer-common: &peer-common
  <<: *common
  image: hyperledger/fabric-peer:2.5
  command: peer node start
  working_dir: /root

x-couchdb-common: &couchdb-common
  <<: *common
  image: couchdb:3.3
  env_file:
    - ./environment/couchdb.env

services:

  # Orderer 0
  orderer0.trade.com:
    <<: *orderer-common
    container_name: orderer0.trade.com
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.trade.com:9443
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer0.trade.com:/var/hyperledger/production/orderer
    ports: [ 7050:7050, 7053:7053, 9443:9443]

  # Orderer 1
  orderer1.trade.com:
    <<: *orderer-common
    container_name: orderer1.trade.com
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.trade.com:9444
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer1.trade.com:/var/hyperledger/production/orderer
    ports: [ 8050:8050, 8053:8053, 9444:9444 ]

  # Orderer 2
  orderer2.trade.com:
    <<: *orderer-common
    container_name: orderer2.trade.com
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.trade.com:9445
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer2.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer2.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer2.trade.com:/var/hyperledger/production/orderer
    ports: [ 9050:9050, 9053:9053, 9445:9445 ]

  # CouchDB for Peer0 Org1
  couchdb0.org1:
    <<: *couchdb-common
    container_name: couchdb0.org1
    ports: [ 5984:5984 ]

  # Peer0 Org1
  peer0.org1.trade.com:
    <<: *peer-common
    container_name: peer0.org1.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer0-org1.env
    depends_on:
      - couchdb0.org1
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer0.org1.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer0.org1.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.trade.com:/var/hyperledger/production
    ports: [ 7051:7051, 9446:9446 ]

  # CouchDB for Peer1 Org1
  couchdb1.org1:
    <<: *couchdb-common
    container_name: couchdb1.org1
    ports: [ 6984:5984 ]

  # Peer1 Org1
  peer1.org1.trade.com:
    <<: *peer-common
    container_name: peer1.org1.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer1-org1.env
    depends_on:
      - couchdb1.org1
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer1.org1.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer1.org1.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org1.trade.com:/var/hyperledger/production
    ports: [ 8051:8051, 9447:9447 ]

  # CouchDB for Peer2 Org1
  couchdb2.org1:
    <<: *couchdb-common
    container_name: couchdb2.org1
    ports: [ 7984:5984 ]

  # Peer2 Org1
  peer2.org1.trade.com:
    <<: *peer-common
    container_name: peer2.org1.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer2-org1.env
    depends_on:
      - couchdb2.org1
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer2.org1.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer2.org1.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer2.org1.trade.com:/var/hyperledger/production
    ports: [ 10051:10051, 9448:9448 ]

  # CouchDB for Peer0 Org2
  couchdb0.org2:
    <<: *couchdb-common
    container_name: couchdb0.org2
    ports: [ 8984:5984 ]

  # Peer0 Org2
  peer0.org2.trade.com:
    <<: *peer-common
    container_name: peer0.org2.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer0-org2.env
    depends_on:
      - couchdb0.org2
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer0.org2.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer0.org2.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.trade.com:/var/hyperledger/production
    ports: [ 9051:9051, 9449:9449 ]

  # CouchDB for Peer1 Org2
  couchdb1.org2:
    <<: *couchdb-common
    container_name: couchdb1.org2
    ports: [ 9984:5984 ]

  # Peer1 Org2
  peer1.org2.trade.com:
    <<: *peer-common
    container_name: peer1.org2.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer1-org2.env
    depends_on:
      - couchdb1.org2
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer1.org2.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer1.org2.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org2.trade.com:/var/hyperledger/production
    ports: [ 11051:11051, 9450:9450 ]

  # CouchDB for Peer2 Org2
  couchdb2.org2:
    <<: *couchdb-common
    container_name: couchdb2.org2
    ports: [ 10984:5984 ]

  # Peer2 Org2
  peer2.org2.trade.com:
    <<: *peer-common
    container_name: peer2.org2.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer2-org2.env
    depends_on:
      - couchdb2.org2
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer2.org2.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer2.org2.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer2.org2.trade.com:/var/hyperledger/production
    ports: [ 12051:12051, 9451:9451 ]

  # CouchDB for Peer0 Org3
  couchdb0.org3:
    <<: *couchdb-common
    container_name: couchdb0.org3
    ports: [ 11984:5984 ]

  # Peer0 Org3
  peer0.org3.trade.com:
    <<: *peer-common
    container_name: peer0.org3.trade.com
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer0-org3.env
    depends_on:
      - couchdb0.org3
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer0.org3.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer0.org3.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org3.trade.com:/var/hyperledger/production
    ports: [ 13051:13051, 9452:9452 ]

  # CouchDB for Peer1 Org3
  couchdb1.org3:
    <<: *couchdb-common
    container_name: couchdb1.org3
    ports: [ 12984:5984 ]

  # Peer1 Org3
  peer1.org3.trade.com:
    <<: *peer-common
    container_name: peer1.org3.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer1-org3.env
    depends_on:
      - couchdb1.org3
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer1.org3.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer1.org3.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org3.trade.com:/var/hyperledger/production
    ports: [ 14051:14051, 9453:9453 ]

  # CouchDB for Peer2 Org3
  couchdb2.org3:
    <<: *couchdb-common
    container_name: couchdb2.org3
    ports: [ 13984:5984 ]

  # Peer2 Org3
  peer2.org3.trade.com:
    <<: *peer-common
    container_name: peer2.org3.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer2-org3.env
    depends_on:
      - couchdb2.org3
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer2.org3.trade.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer2.org3.trade.com/tls:/etc/hyperledger/fabric/tls
      - peer2.org3.trade.com:/var/hyperledger/production
    ports: [ 15051:15051, 9454:9454 ]

  # CLI tool
  cli:
    <<: *common
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    env_file:
      - ./environment/cli.env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./../chaincode:/opt/gopath/src/github.com/chaincode
      - ./../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    depends_on:
      - peer0.org1.trade.com
      - peer0.org2.trade.com
      - peer0.org3.trade.com
