version: '3.7'

volumes:
  orderer0.trade.com:
  orderer1.trade.com:
  orderer2.trade.com:
  peer0.org1.trade.com:
  peer1.org1.trade.com:
  peer2.org1.trade.com:
  peer0.org2.trade.com:
  peer1.org2.trade.com:
  peer2.org2.trade.com:
  peer0.org3.trade.com:
  peer1.org3.trade.com:
  peer2.org3.trade.com:

networks:
  trade:
    name: trade

services:

  # Orderer 0
  orderer0.trade.com:
    container_name: orderer0.trade.com
    image: hyperledger/fabric-orderer:2.5
    env_file:
      - ./environment/orderer.env
      - ./environment/orderer0.env
    working_dir: /root
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer0.trade.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - trade

  # Orderer 1
  orderer1.trade.com:
    container_name: orderer1.trade.com
    image: hyperledger/fabric-orderer:2.5
    env_file:
      - ./environment/orderer.env
      - ./environment/orderer1.env
    working_dir: /root
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer1.trade.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
      - 8053:8053
      - 9444:9444
    networks:
      - trade

  # Orderer 2
  orderer2.trade.com:
    container_name: orderer2.trade.com
    image: hyperledger/fabric-orderer:2.5
    env_file:
      - ./environment/orderer.env
      - ./environment/orderer2.env
    working_dir: /root
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer2.trade.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer2.trade.com/tls:/var/hyperledger/orderer/tls
      - orderer2.trade.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
      - 9053:9053
      - 9445:9445
    networks:
      - trade

  # CouchDB for Peer0 Org1
  couchdb0.org1:
    container_name: couchdb0.org1
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "5984:5984"
    networks:
      - trade

  # Peer0 Org1
  peer0.org1.trade.com:
    container_name: peer0.org1.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer0-org1.env
    depends_on:
      - couchdb0.org1
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer0.org1.trade.com:/etc/hyperledger/fabric
      - peer0.org1.trade.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 9446:9446
    networks:
      - trade

  # CouchDB for Peer1 Org1
  couchdb1.org1:
    container_name: couchdb1.org1
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "6984:5984"
    networks:
      - trade

  # Peer1 Org1
  peer1.org1.trade.com:
    container_name: peer1.org1.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer1-org1.env
    depends_on:
      - couchdb1.org1
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer1.org1.trade.com:/etc/hyperledger/fabric
      - peer1.org1.trade.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 9447:9447
    networks:
      - trade

  # CouchDB for Peer2 Org1
  couchdb2.org1:
    container_name: couchdb2.org1
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "7984:5984"
    networks:
      - trade

  # Peer2 Org1
  peer2.org1.trade.com:
    container_name: peer2.org1.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org1.env
      - ./environment/peer2-org1.env
    depends_on:
      - couchdb2.org1
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.trade.com/peers/peer2.org1.trade.com:/etc/hyperledger/fabric
      - peer2.org1.trade.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 9448:9448
    networks:
      - trade

  # CouchDB for Peer0 Org2
  couchdb0.org2:
    container_name: couchdb0.org2
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "8984:5984"
    networks:
      - trade

  # Peer0 Org2
  peer0.org2.trade.com:
    container_name: peer0.org2.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer0-org2.env
    depends_on:
      - couchdb0.org2
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer0.org2.trade.com:/etc/hyperledger/fabric
      - peer0.org2.trade.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9449:9449
    networks:
      - trade

  # CouchDB for Peer1 Org2
  couchdb1.org2:
    container_name: couchdb1.org2
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "9984:5984"
    networks:
      - trade

  # Peer1 Org2
  peer1.org2.trade.com:
    container_name: peer1.org2.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer1-org2.env
    depends_on:
      - couchdb1.org2
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer1.org2.trade.com:/etc/hyperledger/fabric
      - peer1.org2.trade.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 9450:9450
    networks:
      - trade

  # CouchDB for Peer2 Org2
  couchdb2.org2:
    container_name: couchdb2.org2
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "10984:5984"
    networks:
      - trade

  # Peer2 Org2
  peer2.org2.trade.com:
    container_name: peer2.org2.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org2.env
      - ./environment/peer2-org2.env
    depends_on:
      - couchdb2.org2
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.trade.com/peers/peer2.org2.trade.com:/etc/hyperledger/fabric
      - peer2.org2.trade.com:/var/hyperledger/production
    ports:
      - 12051:12051
      - 9451:9451
    networks:
      - trade

  # CouchDB for Peer0 Org3
  couchdb0.org3:
    container_name: couchdb0.org3
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "11984:5984"
    networks:
      - trade

  # Peer0 Org3
  peer0.org3.trade.com:
    container_name: peer0.org3.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer0-org3.env
    depends_on:
      - couchdb0.org3
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer0.org3.trade.com:/etc/hyperledger/fabric
      - peer0.org3.trade.com:/var/hyperledger/production
    ports:
      - 13051:13051
      - 9452:9452
    networks:
      - trade

  # CouchDB for Peer1 Org3
  couchdb1.org3:
    container_name: couchdb1.org3
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "12984:5984"
    networks:
      - trade

  # Peer1 Org3
  peer1.org3.trade.com:
    container_name: peer1.org3.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer1-org3.env
    depends_on:
      - couchdb1.org3
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer1.org3.trade.com:/etc/hyperledger/fabric
      - peer1.org3.trade.com:/var/hyperledger/production
    ports:
      - 14051:14051
      - 9453:9453
    networks:
      - trade

  # CouchDB for Peer2 Org3
  couchdb2.org3:
    container_name: couchdb2.org3
    image: couchdb:3.3
    env_file:
      - ./environment/couchdb.env
    ports:
      - "13984:5984"
    networks:
      - trade

  # Peer2 Org3
  peer2.org3.trade.com:
    container_name: peer2.org3.trade.com
    image: hyperledger/fabric-peer:2.5
    env_file:
      - ./environment/peer.env
      - ./environment/peer-org3.env
      - ./environment/peer2-org3.env
    depends_on:
      - couchdb2.org3
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org3.trade.com/peers/peer2.org3.trade.com:/etc/hyperledger/fabric
      - peer2.org3.trade.com:/var/hyperledger/production
    ports:
      - 15051:15051
      - 9454:9454
    networks:
      - trade

  # CLI tool
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    env_file:
      - ./environment/cli.env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./../chaincode:/opt/gopath/src/github.com/chaincode
      - ./../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    depends_on:
      - peer0.org1.trade.com
      - peer0.org2.trade.com
      - peer0.org3.trade.com
    networks:
      - trade
